package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.92

import (
	"context"

	"github.com/thiagomaganha/go-clean-architecture/internal/infra/graphql/model"
	"github.com/thiagomaganha/go-clean-architecture/internal/usecase"
)

func (r *mutationResolver) CreateOrder(ctx context.Context, id string, number string, price float64, tax float64) (*model.Order, error) {
	output, err := r.CreateOrderUseCase.Execute(ctx, usecase.CreateOrderInput{
		ID:     id,
		Number: number,
		Price:  price,
		Tax:    tax,
	})
	if err != nil {
		return nil, err
	}
	return &model.Order{
		ID:         output.ID,
		Number:     output.Number,
		Price:      output.Price,
		Tax:        output.Tax,
		FinalPrice: output.FinalPrice,
	}, nil
}

func (r *queryResolver) ListOrders(ctx context.Context, page *int32, limit *int32, query *string) (*model.OrderList, error) {
	input := usecase.ListOrdersInput{}
	if page != nil {
		input.Page = int(*page)
	}
	if limit != nil {
		input.Limit = int(*limit)
	}
	if query != nil {
		input.Query = *query
	}

	output, err := r.ListOrdersUseCase.Execute(ctx, input)
	if err != nil {
		return nil, err
	}

	orders := make([]*model.Order, len(output.Orders))
	for i, o := range output.Orders {
		orders[i] = &model.Order{
			ID:         o.ID,
			Number:     o.Number,
			Price:      o.Price,
			Tax:        o.Tax,
			FinalPrice: o.FinalPrice,
		}
	}

	return &model.OrderList{
		Orders: orders,
		Total:  int32(output.Total),
		Page:   int32(output.Page),
		Limit:  int32(output.Limit),
	}, nil
}

func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
