// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type Order struct {
	ID         string  `json:"id"`
	Number     string  `json:"number"`
	Price      float64 `json:"price"`
	Tax        float64 `json:"tax"`
	FinalPrice float64 `json:"finalPrice"`
}

type OrderList struct {
	Orders []*Order `json:"orders"`
	Total  int32    `json:"total"`
	Page   int32    `json:"page"`
	Limit  int32    `json:"limit"`
}

type Query struct {
}
